baseURL = "https://thuanjzz.github.io/FCAJ-WorkShop/"
relativeURLs = false
canonifyURLs = false
defaultContentLanguage = "en"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = ""
  author = "thienlh@thienlu.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[[menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
